_wandb:
    value:
        cli_version: 0.22.2
        e:
            bfjn9xha2xddckaim918y4jlvag9scpx:
                codePath: src/fine_tuning_clip.py
                codePathLocal: src/fine_tuning_clip.py
                cpu_count: 4
                cpu_count_logical: 4
                disk:
                    /:
                        total: "107362648064"
                        used: "11509792768"
                email: anjali.sarawgi9@gmail.com
                executable: /dss/dsshome1/09/ra47fey3/miniforge3/envs/py39/bin/python
                git:
                    commit: 8eb6be30f4c4ce7f501687592d1b3df59f1fdb80
                    remote: https://github.com/DileepV17/Applied-Deeplearning.git
                host: login-05
                memory:
                    total: "67387498496"
                os: Linux-5.15.0-161-generic-x86_64-with-glibc2.35
                program: /dss/dsshome1/09/ra47fey3/adl_ws/Applied-Deeplearning/src/fine_tuning_clip.py
                python: CPython 3.9.23
                root: /dss/dsshome1/09/ra47fey3/adl_ws/Applied-Deeplearning
                startedAt: "2025-12-05T15:32:45.649983Z"
                writerId: bfjn9xha2xddckaim918y4jlvag9scpx
        m: []
        python_version: 3.9.23
        t:
            "1":
                - 1
                - 41
                - 49
                - 63
            "2":
                - 1
                - 41
                - 49
                - 63
            "3":
                - 13
            "4": 3.9.23
            "5": 0.22.2
            "12": 0.22.2
            "13": linux-x86_64
