_wandb:
    value:
        cli_version: 0.22.2
        e:
            hiwiv8vuj3ev78vdyj6ed427q1imrlef:
                codePath: src/fine_tuning_clip.py
                codePathLocal: src/fine_tuning_clip.py
                cpu_count: 128
                cpu_count_logical: 256
                cudaVersion: "12.2"
                disk:
                    /:
                        total: "1887374536704"
                        used: "113719861248"
                email: anjali.sarawgi9@gmail.com
                executable: /dss/dsshome1/09/ra47fey3/miniforge3/envs/py39/bin/python
                git:
                    commit: 8eb6be30f4c4ce7f501687592d1b3df59f1fdb80
                    remote: https://github.com/DileepV17/Applied-Deeplearning.git
                gpu: NVIDIA A100-SXM4-40GB
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "42949672960"
                      name: NVIDIA A100-SXM4-40GB
                      uuid: GPU-556dde72-57b9-98c0-a6c0-88973391074a
                host: mcml-dgx-007
                memory:
                    total: "1081967046656"
                os: Linux-5.15.0-1091-nvidia-x86_64-with-glibc2.35
                program: /dss/dsshome1/09/ra47fey3/adl_ws/Applied-Deeplearning/src/fine_tuning_clip.py
                python: CPython 3.9.23
                root: /dss/dsshome1/09/ra47fey3/adl_ws/Applied-Deeplearning
                slurm:
                    cluster_name: lrz
                    conf: /etc/slurm-llnl/slurm.conf
                    cpus_on_node: "30"
                    gpus_on_node: "1"
                    gtids: "0"
                    job_account: default
                    job_cpus_per_node: "30"
                    job_end_time: "1764956163"
                    job_gid: "3647528"
                    job_gpus: "2"
                    job_id: "5403496"
                    job_name: test.sbatch
                    job_nodelist: mcml-dgx-007
                    job_num_nodes: "1"
                    job_partition: mcml-dgx-a100-40x8
                    job_qos: mcml
                    job_start_time: "1764948963"
                    job_uid: "4390451"
                    job_user: ra47fey3
                    jobid: "5403496"
                    localid: "0"
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: mcml-dgx-007
                    nprocs: "1"
                    ntasks: "1"
                    prio_process: "0"
                    procid: "0"
                    submit_dir: /dss/dsshome1/09/ra47fey3/adl_ws/Applied-Deeplearning
                    submit_host: login-05
                    task_pid: "1812052"
                    tasks_per_node: "1"
                    topology_addr: mcml-dgx-007
                    topology_addr_pattern: node
                startedAt: "2025-12-05T15:36:09.735200Z"
                writerId: hiwiv8vuj3ev78vdyj6ed427q1imrlef
        m: []
        python_version: 3.9.23
        t:
            "1":
                - 1
                - 41
                - 49
                - 63
            "2":
                - 1
                - 41
                - 49
                - 63
            "3":
                - 13
            "4": 3.9.23
            "5": 0.22.2
            "12": 0.22.2
            "13": linux-x86_64
